bebop2: #namespace

    n_actions: 6 # We have 3 actions, Forwards,TurnLeft,TurnRight, STOP

    linear_forward_speed: 0.5 # Spwwed for ging fowards
    angular_turn_speed: 0.05 # Lienare speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right

    init_linear_speed_vector:
      x: 0.0
      y: 0.0
      z: 0.0

    init_angular_turn_speed: 0.0 # Initial angular speed in shich we start each episode



    max_roll: 1.57 # Max roll after which we end the episode
    max_pitch: 1.57 # Max roll after which we end the episode
    max_yaw: inf # Max yaw, its 4 because its bigger the pi, its a complete turn actually the maximum


    closer_to_point_reward: 10 # We give points for getting closer to the desired point
    not_ending_point_reward: 1 # Points given if we just dont crash
    end_episode_points: 200 # Points given when ending an episode


